name: Tests Nightly

on:
  schedule:
    - cron: '30 5 * * *'
  branches:
    - master
    - develop
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Pre-install
              run: |
                  rm -rf node_modules
                  yarn install --frozen-lockfile
                  git submodule init
                  git submodule update
            - name: Compile and Lint
              run: |
                  yarn lint
                  yarn clean
                  sh ./scripts/build-circuit.sh
                  yarn compile
            - name: Run Unit Tests
              run: |
                  yarn test:unit
            - name: Run Integration Tests
              run: |
                  yarn test:integration

    upgradability-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Pre-install
              run: |
                  export
                  yarn install --frozen-lockfile
                  git submodule init
                  git submodule update
            - name: Compile and Lint
              run: |
                  sh ./scripts/build-circuit.sh
            - name: Run Upgrade Tests
              run: |
                  bash ./scripts/test-upgradeability.sh

    kovan-integration:
        if: ${{ false }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Pre-install
              env:
                  KOVAN_ARCHIVE_RPC_ENDPOINT: ${{ secrets.KOVAN_ARCHIVE_RPC_ENDPOINT }}
              run: |
                  yarn
                  yarn run hardhat node --port 18545 --fork KOVAN_ARCHIVE_RPC_ENDPOINT --fork-block-number 28000000 &
            - name: Compile and Lint
              run: |
                  yarn lint
                  yarn clean
                  yarn compile
            - name: Run Kovan Tests
              run: |
                  yarn test:kovan-integration

