name: Security Tests Run Nightly

on:
  schedule:
    - cron:  '30 2 * * *'

jobs:
    analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: '3.7'
            - name: Pre-install
              run: |
                  rm -rf node_modules
                  yarn install --frozen-lockfile
                  git submodule init
                  git submodule update
            - name: Run Slither
              run: |
                  pip install slither-analyzer
                  yarn clean
                  yarn security:slither
                  echo '\n\nSLITHER REPORT :rocket:\n\n' >> $GITHUB_STEP_SUMMARY
                  cat slitherReport.txt >> $GITHUB_STEP_SUMMARY
            - name: Archive Slyther report
              uses: actions/upload-artifact@v3
              with:
                  name: slither-report
                  path: slitherReport.txt
            - name: Compile
              run: |
                  yarn clean
                  yarn compile
            - name: Flattening contracts
              run: |
                  sh ./scripts/hardhat-flattener.sh
            - name: Run Mythril
              run: |
                  pip install mythril
                  yarn security:mythril
                  echo '\n\nMYTHRIL REPORT :rocket:\n\n' >> $GITHUB_STEP_SUMMARY
                  cat mythrilReport.txt >> $GITHUB_STEP_SUMMARY
            - name: Archive Mythril report
              uses: actions/upload-artifact@v3
              with:
                  name: mythril-report
                  path: mythrilReport.txt
              env:
                  NODE_OPTIONS: "--max-old-space-size=7500"
