name: Security Tests Run Nightly

# TODO: ENABLE NIGHTLY EXECUTION WHEN TESTS ARE OKAY
#on:
#  schedule:
#    - cron:  '30 2 * * *'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
            python-version: '3.7'
      - name: Pre-install
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
          git submodule init
          git submodule update
      - name: Compile and Lint
        run: |
          yarn lint
          yarn clean
          yarn compile
      - name: Flattening contracts
        run: |
          sh ./scripts/hardhat-flattener.sh
        env:
          NODE_OPTIONS: "--max-old-space-size=7500"

  slither:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Slither
        run: |
            pip install slither-analyzer
            yarn security:slither
            cat slitherReport.txt
  mythril:
      needs: build
      runs-on: ubuntu-latest
      steps:
          - name: Run Mythril
            run: |
                pip install mythril
                myth --version
                yarn security:mythril
                cat mythrilReport.txt
