name: Security Tests Run Nightly

# TODO: ENABLE NIGHTLY EXECUTION WHEN TESTS ARE OKAY
#on:
#  schedule:
#    - cron:  '30 2 * * *'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Pre-install
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
          git submodule init
          git submodule update
      - name: Compile and Lint
        run: |
          yarn lint
          yarn clean
          sh ./scripts/build-circuit.sh
          yarn compile
        env:
          NODE_OPTIONS: "--max-old-space-size=7500"

  slither:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          node-version: 14
          sarif: results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

#  mythril:
#      runs-on: ubuntu-latest
#      needs: build
#      steps:
#          - name: Run Slither
#            uses: crytic/slither-action@v0.1.1
#            id: slither
#            continue-on-error: true
